# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "acwilan"
    labels:
      - "dependencies"
      - "dependabot"
    reviewers:
      - "acwilan"
