openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
paths:
  /api.weather.local:
    post:
      summary: Get Weather Information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  example: "New York"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    type: number
                    example: 25.6
                  humidity:
                    type: number
                    example: 65
                  windSpeed:
                    type: number
                    example: 10.5
                  condition:
                    type: string
                    example: "Cloudy"